### ISSUE TITLE
Create browser bundle

### ISSUE THREAD

**Issue by amitguptagwl** [node-muneem/fast-freeze#1]
Use browserify or your favorite npm package to generate browser bundle for this library. Don't complex this tasl by using webpack or using any task runner etc.

> [Bookmark](https://github.com/node-muneem/fast-freeze/stargazers) this package

**Comment by guimochila** [comment]
Can I have this one?! I just want to start to contributing to open source community.

**Comment by amitguptagwl** [comment]
Sure.

**Comment by guimochila** [comment]
I have created a PR #3 for this issue. =)
